Yes, there is a difference in the data types of the variables list_ and array_list.

list_ is a Python list that contains string elements.

array_list is a NumPy array created from that list. Even though the elements are the same, the type of container (list vs. array) is different, and so are their data types.

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']  # Corrected quotation marks
array_list = np.array(object=list_)

# Print data types
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

# To check the data type of elements in the NumPy array
print("Data type of elements in array_list:", array_list.dtype)


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>
Data type of elements in array_list: <U1


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']  # Corrected quotes
array_list = np.array(object=list_)

# Print data types of each element in list_
print("Data types of elements in list_:")
for item in list_:
    print(f"{item} -> {type(item)}")

# Print data types of each element in array_list
print("\nData types of elements in array_list:")
for item in array_list:
    print(f"{item} -> {type(item)}")


Data types of elements in list_:
1 -> <class 'str'>
2 -> <class 'str'>
3 -> <class 'str'>
4 -> <class 'str'>
5 -> <class 'str'>

Data types of elements in array_list:
1 -> <class 'numpy.str_'>
2 -> <class 'numpy.str_'>
3 -> <class 'numpy.str_'>
4 -> <class 'numpy.str_'>
5 -> <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)




ans. Yes, there will be a difference in the data types of the elements present in list_ and array_list after converting the elements in array_list to integers using:



In [3]:
import numpy as np

# Original list with string elements
list_ = ['1', '2', '3', '4', '5']

# NumPy array with integer dtype
array_list = np.array(object=list_, dtype=int)

# Print data types of each element in list_
print("Data types of elements in list_:")
for item in list_:
    print(f"{item} -> {type(item)}")

# Print data types of each element in array_list
print("\nData types of elements in array_list:")
for item in array_list:
    print(f"{item} -> {type(item)}")


Data types of elements in list_:
1 -> <class 'str'>
2 -> <class 'str'>
3 -> <class 'str'>
4 -> <class 'str'>
5 -> <class 'str'>

Data types of elements in array_list:
1 -> <class 'numpy.int64'>
2 -> <class 'numpy.int64'>
3 -> <class 'numpy.int64'>
4 -> <class 'numpy.int64'>
5 -> <class 'numpy.int64'>


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [4]:
import numpy as np

# Define the nested list and convert it to a NumPy array
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Print shape and size
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [5]:
import numpy as np

# Create a 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))

# Print the array
print("3x3 Zero Matrix:")
print(zero_matrix)


3x3 Zero Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [ ]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the matrix
print("5x5 Identity Matrix:")
print(identity_matrix)
